  server.port: 8080

  spring:
  application:
    name: Contrato

  # ID da pasta do Google Drive
  google:
    drive:
      contrato-aberto-id: 1qVH02WANzIobXRxeA5RzrZCXMbXhWbYq
      contrato-cancelado-id: 1s9Pp3GTKkpTXhPw2BzOxqTTr0lNYrbnX
      contrato-realizado-id: 1ly7YNtJ53HmcteZnRK9cSGX-e7NwJR12
      contrato-quitado-id: 1Uhe35hC7hSf4HtcEHxlX9xRaycK4IDBv

  logging:
    level:
      org.springframework.web: DEBUG
      com.adoleta: DEBUG

  server:
    error:
      include-stacktrace: always
      include-message: always
